---
- name: Install OpenVPN and EasyRSA
  apt:
    name:
      - openvpn
      - easy-rsa
    update_cache: yes
    state: present

- include_tasks: pki.yml
- include_tasks: server.yml
- include_tasks: client.yml